$(document).ready(function(){
	$("#button1").click(function(){
	  $(".para").hide();
	  $("#para1").show();
	});
	$("#button2").click(function(){
	  $(".para").hide();
	  $("#para2").show();
	});
	$("#button3").click(function(){
	  $(".para").hide();
	  $("#para3").show();
	});
	$("#button4").click(function(){
	  $(".para").hide();
	  $("#para4").show();
	});
	$("#button5").click(function(){
	  $(".para").hide();
	  $("#para5").show();
	});
});